### ISSUE TITLE
سلامی از سمت دوست قدیمی

### ISSUE THREAD

**Issue by MrYazdan** [Ayazadeh/VueCourseWithMaximilian#1]
سلام محمد جان
vue ورژن ۲ دیگه خیلی کم استفاده میشه
مخصوصا با ریلیز رسمی دو هفته پیش nuxtدیگه علنا داره کم کاربر میشه
اگر دوست داری این فریمورک قشنگ رو ادامه بدی با ورژن سه ادامه بده دوست من
خواستی بگو داکیومنت و course هایی که خودم دیدم رو بهت معرفی کنم :heart_decoration:

**Comment by Ayazadeh** [comment]
بهه بهه سلام  داش رضای گل ❤، آقا من پروژه ای که دارم میزنم قبلا تا حدودی با
vue2 زدن برا همین از ۲ شروع کردم اما اونم زیاد نمیبینم بیشتر سرچ میکنم تا
راه حل هایی برای تسکایی که میدن بیابم، مهندس بالا سرم میگه کدت مهم نیست فقط
زودتر یه چیزی بیار بالا ارائه بدیم، اما باز هم من سعی میکنم کدام و بهتر و
بهتر کنم. یه دوره از مکسی میلیان از سایت ایران یودمی دانلود کردم که ویو۲ و
ویو۳ رو درس داده داشتم اون و میرفتم جلو، باز اگر دوره بهتری داری بخصوص برای
ناکست ممنونت میشم به من برسانی داداش.

**Comment by Ayazadeh** [comment]
راستی اینم بگم که مهندس گفت اگر پروژه به یه جای استیبلی برسه و نیروی فرانت
بیشتر بهمون بدن من میتونم برم پروژه رو با بروز ترین نسخه ویو و ناکست دوباره
شروع کنم، الان فرانتشون فقط منم دوماه دیگه یکی دیگه هم میاد که اونم خیلی
بلد نیست
